### ISSUE TITLE
Settings not saving in final build

### ISSUE THREAD

**Issue by MerryGrim** [Cesio137/GConfigManager#1]
Topic. All configs working (loading) only in editor. When you buid game, working only RHI.

**Comment by MerryGrim** [comment]
It's not working in config for Developer (where saves in ) build and Shipping (where saves in appdata) as well :<
And yep, checked.
Ah, i'm using Project Launcher for biulding game. 

I'm not good in coding, but i guess problems could be after UE 5.0.1 update:

```
TargetPlatform Names are being standardized. The main change will be WindowsNoEditor → Windows
Developers will need to update their build scripts to use new names (and rarely their DeviceProfiles.ini files):
Windows → WindowsEditor
WindowsNoEditor → Windows
MacNoEditor → Mac
Mac → MacEditor
LinuxNoEditor → Linux
Linux → LinuxEditor
LinuxAArch64NoEditor → LinuxAArch64
```

**Comment by MerryGrim** [comment]
And also. It's adding settings in Engine.ini in any Save folder
For example
```
[Script/Engine.RendererSettings]
r.MSAACount=2
r.AntiAliasingMethod=3
```
But game don't want to read this settings. Tho in editor everything works fine.

**Comment by Cesio137** [comment]
It'll take some time because I can't find a documentation about this

**Comment by Cesio137** [comment]
> Hello~ How it's going?

I'm waiting epic update UE5's documentation to find a solution

**Comment by MerryGrim** [comment]
And, uh, 5.1 update when? ><

**Comment by Cesio137** [comment]
> And, uh, 5.1 update when? ><

I'm waiting for hotfix first
